// export { default as Navbar } from './Navbar'
// export { default as Sidebar } from './Sidebar/index.vue'
// export { default as TagsView } from './TagsView'
export { default as AppMain } from './AppMain'
export { default as SideBar } from './SideBar'
export { default as NavBar } from './NavBar'
export { default as RightArea } from './RightArea'